### PR TITLE
RSAF A330MRTT livery v1

### PR DESCRIPTION
**Pull request by SGFlightSimmerYT**
My first livery for flightgear

### CODE REVIEW

**Comment by SammySkycrafts** [comment]
Looks nice! Though you seem to be missing a few (some larger than others) elements of the livery. There doesnt appear to be the tail flash, Singapore flag, ot the wavy artwork on the engines. If you take a look at [these](https://www.maphotosg.com/republic-of-singapore-air-force-a330-mrtt-arrives-home/) you'll probably see.

**Comment by SGFlightSimmerYT** [comment]
> Looks nice! Though you seem to be missing a few (some larger than others) elements of the livery. There doesnt appear to be the tail flash, Singapore flag, ot the wavy artwork on the engines. If you take a look at [these](https://www.maphotosg.com/republic-of-singapore-air-force-a330-mrtt-arrives-home/) you'll probably see.

yep ok I will fix

**Comment by SGFlightSimmerYT** [comment]
@SammySkycrafts livery is now updated :)

**Comment by SGFlightSimmerYT** [comment]
v1.02 update is out, fixing engine decals
(when will the other 6 pull requests be closed?)

**Comment by JMaverick16** [comment]
Hi! I just managed to see this. Livery looks really good, I can add it right away unless you think there are still a few things that need to be done

**Comment by SGFlightSimmerYT** [comment]
> Hi! I just managed to see this. Livery looks really good, I can add it right away unless you think there are still a few things that need to be done

sure go ahead

**Pull request merged**
