### PR TITLE
Will the cockpit be redisigned

### PR DESCRIPTION
**Pull request by mohamedaissa**
i sawed that the cockpit of this plane is like the one in the A320
The Overhead is 90 % accurate  it just doesn't have the fuel dumping buttons
But the autobrakes, gears indicators ,clock... are not in the correct place.
a picture  of the A330 cockpit:
xwrw4zlj7c511

Sorry if i did something wrong idk how to use Git Hub

### CODE REVIEW

**Comment by mohamedaissa** [comment]
thanks for your answer

**Comment by JMaverick16** [comment]
Haven't we merged these already?

**Comment by mohamedaissa** [comment]
i didn't post the cockpit of this A330 sorry
As you can see there is a difference in the position of the autobrakes button andclock ....
Or maybe i'm missing something
fgfs-20201111195135
xwrw4zlj7c511

**Comment by mohamedaissa** [comment]
Or Did you  redisign it

**Comment by JMaverick16** [comment]
Different versions have different cockpit layouts

**Comment by mohamedaissa** [comment]
yeah i've searched for the cockpit of the -200 and -300 and they have a pretty similar cockpit
But the problem of this cockpit is the position of the gear indicator.
i've searched and it's the same in every variant of the A330

**Comment by mohamedaissa** [comment]
and y did you close this 
Maybe other new developpers could come and want to change the cockpit

**Comment by mohamedaissa** [comment]
> Different versions have different cockpit layouts

So you are not redoing this cockpit

This plane is DEAD no ?

**Comment by Marsdolphin** [comment]
Please do not spam comments on a pull request that wants to merge things that already exists in the repository. Also, please report any problems in the issue section.  Be aware that most of us have our own priorities, and the updates of the A330 largely depends on that of the A320. Features of the A320 will be backported and converted to the A330 when ready. Cockpit updates will come when that happens. Additionally, also be aware that 3D modelling changes takes a long time and a lot of effort to do. Currently, most developers of the Airbus A330/A320 are busy. If you want changes to happen immediately, the best thing you want to do is not to complain here but to learn blender, xml and make the changes yourself. Then, come to us and we will review your changes. If you do not want to learn the skills required, then please be patient for us to be done with the A320.

**Comment by merspieler** [comment]
> [] for us to be done with the A320.

First I heard of that the main devs of the A330 work on the A320 :D 

Just for completeness, I'll open an issue to keep track of this pending change.

**Comment by Marsdolphin** [comment]
Oh yeah, lol 😂

**Pull request closed without merging**
