### PR TITLE
Reshape throttles and trim wheels

### PR DESCRIPTION
**Pull request by Kasluk24**
According to  #18:
- Thrust lever shape and trim wheel

From my point of view, the modelling is complete. I am still not sure about the scale of the trim wheel in reality. So if anyone has a good picture, I'll be happy to use that.

I am now opening this pull request so that you can give feedback already if you want. The textures are not final yet. The engine mode switch needs to be adjusted again along with the lower pedestal. I'll post a comment when I'm ready to merge.

### CODE REVIEW

**Comment by Kasluk24** [comment]
For me, it's now ready to be merged. I couldn't solve the problem with the trim wheel, but I think it's still better than the wheel from the A320 in an A330.

**Comment by Octal450** [comment]
Merged... sorry it took so long...

**Comment by Octal450** [comment]
Great job. If you were to continue the cockpit work, I could be encouraged into continuing development of the A330...

**Comment by Kasluk24** [comment]
Thanks, Josh. It looks like I missed something here. 
At the moment, I’m no longer working on FlightGear aircraft; I’m busy with other projects. But perhaps one day I’ll get back to it.

**Pull request merged**
